name: ci

on:
  push:
    branches:
      - "master"

jobs:
  docker:
    strategy:
      matrix:
        include:
          - version: 8.8.20
          - version: 8.8.31
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: gridgain-community
          platforms: linux/amd64,linux/arm64
          push: true
          tags: rynffoll/gridgain-community:${{ matrix.version }}
          build-args: |
            VERSION=${{ matrix.version }}
